---
title: "GoogleVis"
author: "Yuchan Jeong"
date: "`r Sys.Date()`"
output: html_document
---

```{r, gv, result = "asis", chache = TRUE}
suppressPackageStartupMessages(library(googleVis))

M <- gvisMotionChart(Fruits, "Fruit", "Year",
                     options = list(width = 600, height = 400))

plot(M)
print(M, "chart")

# Since Adobe Flash has been retired and is no longer supported, gvisMotionChart does not work anymore
```
```{r}
# Interactive Maps
G <- gvisGeoChart(Exports, locationvar = "Country", colorvar = "Profit", options = list(width = 1200, height = 800))

plot(G)
print(G, "chart")
```

```{r results='asis', tidy=FALSE}
## Line chart with options set
df <- data.frame(label=c("US", "GB", "BR"), val1=c(1,3,4), val2=c(23,12,32))
Line <- gvisLineChart(df, xvar="label", yvar=c("val1","val2"),
        options=list(title="Hello World", legend="bottom",
                titleTextStyle="{color:'red', fontSize:18}",                         
                vAxis="{gridlines:{color:'red', count:3}}",
                hAxis="{title:'My Label', titleTextStyle:{color:'blue'}}",
                series="[{color:'green', targetAxisIndex: 0}, 
                         {color: 'blue',targetAxisIndex:1}]",
                vAxes="[{title:'Value 1 (%)', format:'##,######%'}, 
                                  {title:'Value 2 (\U00A3)'}]",                          
                curveType="function", width=500, height=300                         
                ))
```

```{r results='asis'}
## Line chart with options
plot(Line)
```

```{r}
G <- gvisGeoChart(Exports, "Country", "Profit", options = list(width = 200, height = 270))
T1 <- gvisTable(Exports, options = list(widt = 200, height = 270))
M <- gvisMotionChart(Fruits, "Fruit", "Year", options = list(width = 400, height = 370))
GT <- gvisMerge(G, T1, horizontal = FALSE)
GTM <- gvisMerge(GT, M, horizontal = TRUE, tableOptions = "bgcolor=\"#CCCCCC\" cellspacing = 10")
```

