---
title: "plotly"
author: "Yuchan Jeong"
date: "`r Sys.Date()`"
output: html_document
---

# Scatterplot Color
```{r}
library(plotly)
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, mode = "markers", color = as.factor(mtcars$cyl))
```
# Continous Color
```{r}
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, mode = "markers", color = mtcars$disp)
```
# Scatterplot Sizing
```{r}
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, mode = "markers", color = as.factor(mtcars$cyl), size = mtcars$hp)
```
# 3D Scatterplot
```{r}
set.seed(42)
temp <- rnorm(100, mean = 30, sd = 5)
pressue <- rnorm(100)
dtime <- 1:100
plot_ly(x = temp, y = pressue, z = dtime,
        type = "scatter3d", mode = "markers", color = temp)
```
# Line Graph
```{r, eval = FALSE}
data("airmiles")
plot_ly(x = time(airmiles), y = airmiles, mode = "lines")
```
# Multi Line Graph
```{r}
library(plotly)
library(tidyr)
library(dplyr)
data("EuStockMarkets")

stocks <- as.data.frame(EuStockMarkets) %>% 
  gather(index, price) %>% # Switch into long format
  mutate(time = rep(time(EuStockMarkets), 4))

plot_ly(stocks, x = stocks$time, y = stocks$price, color = stocks$index, mode = "lines")
```
# Boxplot
```{r}
plot_ly(iris, y = iris$Petal.Length, color = iris$Species, type = "box")
```
# Heatmap
```{r}
terrain1 <- matrix(rnorm(100*100), nrow = 100, ncol = 100)
plot_ly(z = terrain1, type = "heatmap")
```
# 3D Surface
```{r}
terrain2 <- matrix(sort(rnorm(100*100)), nrow = 100, ncol = 100)
plot_ly(z = terrain2, type = "surface")
```
# Choropleth Maps

```{r}
state_pop <- data.frame(State = state.abb, Pop = as.vector(state.x77[,1]))
state_pop$hover <- with(state_pop, paste(State, '<br>', "Population:", Pop))
borders <- list(color = toRGB("red"))
map_options <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB("white")
)

plot_ly(state_pop, z = Pop, text = hover, locations = State,
        type = 'choropleth', locationmode = 'USA-states',
        color = Pop, colors = 'Blues', marker = list(line = borders)) %>% 
  layout(title = 'US Population in 1975', geo = map_options)
```

# ggplot2
```{r}
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000), ]

p <- ggplot(data = d, aes(x = carat, y = price)) +
  geom_point(aes(text = paste("Clarity:", clarity)), size = 4) +
  geom_smooth(aes(colour = cut, fill = cut)) + facet_wrap(~ cut)

(gg <- ggplotly(p))

plotly_POST(gg) #Upload on plotly website
```

